apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: hashicorp/http-echo
        name: http-echo
        args: ["-text=Hello From the First Application !"]
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-12-24T07:58:54Z"
  labels:
    app: app1
  name: app1
  namespace: default
  resourceVersion: "2549"
  uid: e9befa53-2f06-4afe-8557-f5cdaad417e3
spec:
  clusterIP: 10.43.152.40
  clusterIPs:
  - 10.43.152.40
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: app1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5678
  selector:
    app: app1
status:
  loadBalancer: {}
