apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42-playground-gitlab
  namespace: argocd
spec:
  project: bonus-project
  source:
    repoURL: 'http://gitlab.gitlab.svc.cluster.local/root/platform-foundation.git'
    targetRevision: HEAD
    path: p3/manifests/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
